spring:
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL;
    username: SA
    password:
  sql:
    init:
      mode: always
      data-locations: classpath:db/h2/data.sql
